### ISSUE TITLE
Vote event not working as expected

### ISSUE THREAD

**Issue by c0nsol3** [deadlock-delegate/notifier#6]
```
3|ark-relay  | TypeError: Cannot read property 'walletManager' of undefined
3|ark-relay  |     at Object.walletUnvote [as wallet.unvote] (/home/ark/.config/yarn/global/node_modules/@deadlock-delegate/notifier/lib/app.js:119:40)
3|ark-relay  |     at Object.<anonymous> (/home/ark/.config/yarn/global/node_modules/@deadlock-delegate/notifier/lib/app.js:62:68)
3|ark-relay  |     at EventEmitter.emit (events.js:228:7)
3|ark-relay  |     at VoteTransactionHandler.emitEvents (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-transactions/dist/handlers/vote.js:76:17)
3|ark-relay  |     at DatabaseService.emitTransactionEvents (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-database/dist/database-service.js:545:100)
3|ark-relay  |     at async DatabaseService.applyBlock (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-database/dist/database-service.js:65:13)
3|ark-relay  |     at async AcceptBlockHandler.execute (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-blockchain/dist/processor/handlers/accept-block-handler.js:9:13)
3|ark-relay  |     at async Blockchain.processBlocks (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-blockchain/dist/blockchain.js:317:33)
```

**Comment by c0nsol3** [comment]
Error is raised because `this.database` is `undefined`: https://github.com/deadlock-delegate/notifier/blob/master/lib/app.js#L110

**Comment by c0nsol3** [comment]
Should be fixed by https://github.com/deadlock-delegate/notifier/commit/01822f2a174b766f4c744270caa908fca7413923
